language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libatlas-dev liblapack-dev gfortran
    - sudo apt-get install -qq libfreeimage3
    - sudo apt-get install -qq libpng12-dev libtiff4-dev libwebp-dev

    - pip install -r tests-requirements.txt
install:
    - make debug
script:
    coverage run --source=mahotas setup.py test
after_success:
    coveralls
