sudo: false
language: python
cache:
  ccache: true
  directories:
    - $HOME/.ccache
    - $HOME/miniconda

before_cache:
    - ccache --show-stats
    - ccache --zero-stats

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  global:
    - USE_CCACHE=1
  matrix:
    - NUMPY_VERSION=1.10
    - NUMPY_VERSION=1.11
    - NUMPY_VERSION=1.12
    - NUMPY_VERSION=1.13


# Conda does not have a numpy=1.10 for Python 3.6:
matrix:
  exclude:
    - python: "3.6"
      env: NUMPY_VERSION=1.10
before_install:
    - .travis/travis_before_install.sh
install:
    - export PATH=$HOME/miniconda/bin:$PATH
    - export PATH=/usr/lib/ccache:$PATH
    - .travis/travis_install.sh
script:
    - source activate condaenv
    - coverage run --source=mahotas setup.py test
after_success:
    - source activate condaenv
    - coveralls
