language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-numpy cython libatlas-dev liblapack-dev gfortran
    - sudo apt-get install -qq python-scipy libhdf5-serial-1.8.4 libhdf5-serial-dev
install:
  - "pip install nose"
  - "make debug"
# command to run tests
script: nosetests
