language: python
python:
  - "2.7_with_system_site_packages"
  - "3.3"
  - "3.4"
before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda
    - sudo apt-get update -qq
    - sudo apt-get install -qq libatlas-dev liblapack-dev gfortran
    - sudo apt-get install -qq libfreeimage3
    - sudo apt-get install -qq libpng12-dev libtiff4-dev libwebp-dev

install:
    - conda create  --yes -n condaenv python=$TRAVIS_PYTHON_VERSION numpy=1.9
    - conda install --yes -n condaenv python=$TRAVIS_PYTHON_VERSION scipy matplotlib PIL nose pip
    - source activate condaenv
    - pip install --quiet coveralls
    - pip install --quiet imread
    - make debug
script:
    coverage run --source=mahotas setup.py test
after_success:
    coveralls
